FROM python:3.9-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        gcc \
        python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ofertas/requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY ./ofertas ./ofertas

CMD ["uvicorn", "ofertas.app.main:app", "--host", "0.0.0.0", "--port", "8000"]