version: "3.9"

services:
  productos:
    image: falofer0405/productos:latest
    container_name: productos
    ports:
      - "8000:8000"
    volumes:
      - ../productos:/app/productos  # Cambiado para apuntar al directorio correcto
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://redpizza:1234@db:5432/productos_db
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/productos"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ofertas:
    image: falofer0405/ofertas:latest
    container_name: ofertas
    ports:
      - "8001:8000"
    volumes:
      - ../ofertas:/app/ofertas  # Cambiado para apuntar al directorio correcto
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://redpizza:1234@db:5432/ofertas_db
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ofertas"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: redpizza
      POSTGRES_PASSWORD: 1234
      POSTGRES_MULTIPLE_DATABASES: productos_db,ofertas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redpizza"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: